import { html, raw } from "hono/html";
import { Layout } from "../layout";
import { highlight } from "../highlight";

const toc = [
  { id: "default", label: "Default" },
  { id: "images", label: "Images" },
  { id: "multiple", label: "Multiple carousels" },
];

const slideColors = [
  "var(--ui-color4-300)",
  "var(--ui-color1-300)",
  "var(--ui-color3-300)",
  "var(--ui-color6-300)",
  "var(--ui-color2-300)",
];

function slides(prefix: string) {
  return slideColors.map(
    (color, i) => html`
      <li>
        <div
          style="background:${color};aspect-ratio:16/9;border-radius:12px;display:flex;align-items:center;justify-content:center;font-weight:600;color:var(--ui-neutral-950)"
        >
          ${prefix} ${i + 1}
        </div>
      </li>
    `,
  );
}

export async function CarouselPage(path: string) {
  return Layout({
    title: "Carousel",
    path,
    toc,
    content: html`
      <div class="prose">
        <hgroup>
          <h1>Carousel</h1>
          <p>
            A scroll-snap carousel with navigation buttons and dots, entirely
            generated by the browser from CSS alone: no
            <code>&lt;button&gt;</code> markup, no JavaScript. It's built on the
            <code>::scroll-button()</code>, <code>::scroll-marker</code>, and
            <code>scroll-marker-group</code> CSS features described in the
            <a
              href="https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Overflow/Carousels"
              target="_blank"
              rel="noopener"
              >MDN CSS carousels guide</a
            >. These are very new and currently only ship in Chromium-based
            browsers.
          </p>
        </hgroup>

        <h2 id="default">Default</h2>
        <p>
          A plain <code>&lt;ul class="carousel"&gt;</code> of
          <code>&lt;li&gt;</code> slides. The previous/next buttons and the dots
          below are generated automatically, they're not real elements in the
          markup. The buttons disable themselves at the ends via
          <code>:disabled</code>, and the active dot is tracked with
          <code>:target-current</code>. Each <code>&lt;li&gt;</code> needs a
          <code>data-accname</code> attribute: an empty
          <code>::scroll-marker</code> content string gives it a blank
          accessible name and breaks it, so its text comes from that attribute
          and is hidden visually with <code>text-indent</code>.
        </p>
      </div>
      <div class="example">
        <div class="preview" style="width:100%">
          <ul
            class="carousel"
            style="width:100%;max-width:480px;margin:auto;--carousel-anchor:--carousel-default"
          >
            ${slides("Slide")}
          </ul>
        </div>
        <div class="code-block">
          ${raw(
            await highlight(`<ul class="carousel" style="--carousel-anchor: --carousel-default">
  <li>Slide 1</li>
  <li>Slide 2</li>
  <li>Slide 3</li>
</ul>`),
          )}
        </div>
      </div>

      <div class="prose">
        <h2 id="images">Images</h2>
        <p>
          Put an <code>&lt;img&gt;</code> directly inside each
          <code>&lt;li&gt;</code> and it's sized to fill the slide
          automatically.
        </p>
      </div>
      <div class="example">
        <div class="preview" style="width:100%">
          <ul
            class="carousel"
            style="width:100%;max-width:480px;margin:auto;--carousel-anchor:--carousel-images"
          >
            <li data-accname="Slide 1">
              <img
                src="https://api.dicebear.com/9.x/glass/svg?seed=carousel-1"
                alt=""
              />
            </li>
            <li data-accname="Slide 2">
              <img
                src="https://api.dicebear.com/9.x/glass/svg?seed=carousel-2"
                alt=""
              />
            </li>
            <li data-accname="Slide 3">
              <img
                src="https://api.dicebear.com/9.x/glass/svg?seed=carousel-3"
                alt=""
              />
            </li>
          </ul>
        </div>
        <div class="code-block">
          ${raw(
            await highlight(`<ul class="carousel" style="--carousel-anchor: --carousel-images">
  <li data-accname="Slide 1"><img src="/slide-1.jpg" alt="" /></li>
  <li data-accname="Slide 2"><img src="/slide-2.jpg" alt="" /></li>
  <li data-accname="Slide 3"><img src="/slide-3.jpg" alt="" /></li>
</ul>`),
          )}
        </div>
      </div>

      <div class="prose">
        <h2 id="multiple">Multiple carousels</h2>
        <p>
          The buttons and dots are positioned with CSS anchor positioning, which
          needs a unique <code>anchor-name</code> per carousel. A single
          carousel works out of the box, but with more than one on the same
          page, set <code>--carousel-anchor</code> inline to a unique value on
          each so their buttons don't anchor to the wrong carousel.
        </p>
      </div>
      <div class="example">
        <div class="preview" style="width:100%;flex-direction:column;gap:2rem">
          <ul
            class="carousel"
            style="width:100%;max-width:480px;margin:auto;--carousel-anchor:--carousel-a"
          >
            ${slides("A")}
          </ul>
          <ul
            class="carousel"
            style="width:100%;max-width:480px;margin:auto;--carousel-anchor:--carousel-b"
          >
            ${slides("B")}
          </ul>
        </div>
        <div class="code-block">
          ${raw(
            await highlight(`<ul class="carousel" style="--carousel-anchor: --carousel-a">
  <li data-accname="A1">A1</li>
  <li data-accname="A2">A2</li>
</ul>

<ul class="carousel" style="--carousel-anchor: --carousel-b">
  <li data-accname="B1">B1</li>
  <li data-accname="B2">B2</li>
</ul>`),
          )}
        </div>
      </div>
    `,
  });
}
